/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedHomeRouteImport } from './routes/(authenticated)/home'
import { Route as authenticatedAddRouteImport } from './routes/(authenticated)/add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/(authenticated)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedHomeRoute = authenticatedHomeRouteImport.update({
  id: '/(authenticated)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedAddRoute = authenticatedAddRouteImport.update({
  id: '/(authenticated)/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/add': typeof authenticatedAddRoute
  '/home': typeof authenticatedHomeRoute
  '/': typeof authenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/add': typeof authenticatedAddRoute
  '/home': typeof authenticatedHomeRoute
  '/': typeof authenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(authenticated)/add': typeof authenticatedAddRoute
  '/(authenticated)/home': typeof authenticatedHomeRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/add' | '/home' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/add' | '/home' | '/'
  id:
    | '__root__'
    | '/login'
    | '/(authenticated)/add'
    | '/(authenticated)/home'
    | '/(authenticated)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  authenticatedAddRoute: typeof authenticatedAddRoute
  authenticatedHomeRoute: typeof authenticatedHomeRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/home': {
      id: '/(authenticated)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/add': {
      id: '/(authenticated)/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof authenticatedAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  authenticatedAddRoute: authenticatedAddRoute,
  authenticatedHomeRoute: authenticatedHomeRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
